[package]
name = "c2rust"
version = "0.1.0"
authors = ["Ronny Wichers Schreur <ronny@cs.ru.nl>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
common = { path = "../common" }

libc = "0.2.0"
